name: Test Rate Limiting

on:
  push:
    branches:
      - main
    paths:
      - "Dockerfile"
      - "test/**"
      - ".github/workflows/test-rate-limiting.yml"
      - ".github/workflows/_test.yml"
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/_test.yml
    permissions:
      contents: read
      pull-requests: write
